### ISSUE TITLE
Memory error while lunching simstar

### ISSUE THREAD

**Issue by BatuhanGencay** [BLG638-Project/final-2021#2]
I receive the error below when I calling the bash script to run simstar.

src/tcmalloc.cc:283] attempt to free invalid pointer 0x7f274e090010

**Comment by ferhatmelih** [comment]
can you report your OS and GPU Model 

and can you check if you can start the simulation without rendering 

    ./SimStar.sh -nullrhi

**Comment by BatuhanGencay** [comment]
I am using Ubuntu 18.04 and Nvidia K40. I also tried running rendering but still got the same error

**Comment by ferhatmelih** [comment]
what is the result of running **nvidia-smi** on terminal. can you report here

**Comment by ferhatmelih** [comment]
if we cannot solve this problem, we can make a zoom session and try to solve it together. 
email me from melih.dal@eatron.com so we can schedule a meeting.

**Comment by BatuhanGencay** [comment]
I made it work somehow by deleting and reinstalling some drivers. Closing this issue.
