### ISSUE TITLE
road_deviation['lat_dev'] returns positive regardless of the cars location to center

### ISSUE THREAD

**Issue by HalitU** [BLG638-Project/final-2021#3]
Hello, I noticed a strange behaviour and I was wondering if it was intended or not.

Whether the car moves in the left side from center of the road, or right side of it, the road_deviation['lat_dev'] value which gives the car distance to the center is always returned as positive from the following call in the simstarEnv.py file.

self.main_vehicle.get_road_deviation_info()

Now if this was intended, then taking the absolute value of the trackPos in the reward calculation is strange, as it will always be positive. Was this the intended implementation? Is there a way to know whether the car is on the left, or right side of center? Angle comes properly as negative or positive according to center, but the distance is always positive so it felt a bit confusing. I havent modified the implementation so this should be the currently expected behavior.

**Comment by resuldagdanov** [comment]
Hi,

In previous version of SimStar trackPos was intended to be from range [-1 to 1]; however, with new version of SimStar v2.0 this confusion is avoided. In the code, the absolute value is taken as it has been left from previous versions.

It was intended to output always positive value.

If you want to know the direction of the vehicle heading, you could you the angle value which gives both negative and positive values.

Thanks.
