### ISSUE TITLE
Collision Detection

### ISSUE THREAD

**Issue by BatuhanGencay** [BLG638-Project/final-2021#6]
Hi, as far as we understand the observation from simstar only contains information about damage of the car for collision detection and once the agent hit an opponent this value becomes true and keeps returning true. Is there any way to detect collision for each time the agent hit an opponent ?

**Comment by ferhatmelih** [comment]
No there is not a method for that. 

I can suggest that you can get the opponent sensor measurements and decide on that by a check of distance. 

in the environment script, you can find the picture of opponent sensor placement. Or, in the DistanceSensorParams, you can enable draw_debug=True and see the rays of the opponent sensor coming out of the sensor.

Then, you can check environment.md for how to use the vehicle by Keyboard. Record the distances that constitute a collision. Then decide if collision has occured by opponent sensor outputs. 

I guess it could be easier if you set other agent speeds to 0. 

Keyboard control is done with W,A,S,D and Q for reverse gear.

**Comment by ferhatmelih** [comment]
I just checked that we did not add keyboard control explanation to environment.md

    self.main_vehicle.set_controller_type(simstar.DriveType.API)

can be changed to 

     self.main_vehicle.set_controller_type(simstar.DriveType.Keyboard)

**Comment by BatuhanGencay** [comment]
OK I will try that. Thank you
