### ISSUE TITLE
Race Rules

### ISSUE THREAD

**Issue by salihgunduz** [BLG638-Project/final-2021#7]
Hello, I have a few questions about the race rules:
1- Are we going to race on the "Dutch" track or randomly?
2- What happens if we deviate the road? Do we have to turn back to the track? Do we eliminate, then, or continue with the same point?
3. How many laps is the race?

**Comment by ferhatmelih** [comment]
Hi,

1. Final race track is not finalized yet. It may not be disclosed. So be ready to race in an unknown track. 
2. Minor and infrequent deviations are OK, about 1 or 2 meters. But any more than that is not acceptable. 
3. Evaluation for a single agent will be made in several laps. However final multi-agent race lap number will depend on the result of the submissions.
