### ISSUE TITLE
Red Arrow

### ISSUE THREAD

**Issue by BatuhanGencay** [BLG638-Project/final-2021#9]
Hi I observed that the red arrow on the starting point of the maps are detected by the opponent sensor that causes weird interaction while finishing lap. Is this a bug or is it supposed to happen on the final race too ?

**Comment by ferhatmelih** [comment]
Hi, we have not noticed that in our tests. Thanks for the warning. 
It will be fixed in final evaluation.
And it should not affect 1 lap test anyway. 
I am closing this issue as I dont think its necessary to upload a new simulation environment only for this fix.
